name: Build and Release ELF

on:
  push:
    branches:
      - main
      - master

jobs:
  build_linux_elf:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Compile Python to ELF and place in RSPG folder
      run: pyinstaller --onefile --distpath RSPG --noconfirm RSPG/RSPG.py

    - name: Store the compiled ELF file
      uses: actions/upload-artifact@v4
      with:
        name: RSPG-elf-binary
        path: RSPG/RSPG
